version: "3.7"
services: 
  mongodb:
    image: mongo:4.0.4
    container_name: mongodb
    ports: 
      - "27017-27019:27017-27019"
    restart: always 
  flask:
    build: .
    container_name: flask
    ports: 
      - "3000-3002:3000-3002"
    links:
      - mongodb
    restart: always
